### ISSUE TITLE
SF.rb January Meetup

### ISSUE THREAD

**Issue by lilliealbert** [sfdotrb/organizing#1]
### Who's got what? :fist:

Venue liaison: @aneyzberg 
Speaker organizer: @stellacotton 
Attendee question/answerer: @sienatime 
Emcee & volunteer wrangler: @aneyzberg 
Online content wrangling: @aneyzberg & @stellacotton 
Other Stuff: @lilliealbert
### Planning Checklist :heavy_check_mark:
- [x] Venue confirmed
- [x] Date confirmed
- [x] 5-7 min speaking slot filled
- [x] 20 min speaking slot #1 filled
- [x] 20 min speaking slot #2 filled
- [x] Event posted to Meetup
- [x] Food / drinks confirmed
- [x] Emcee confirmed - Anna
- [x] Security / checkins wrangler confirmed - Siena

**Comment by aneyzberg** [comment]
Set up - Anna
-  about 50 seats fifty 
- projector/microphone

Logistics
- What time front door locks (will determine check-in upstairs or downstairs) - Anna
- Pro-noun name tags/name tags - Anna
- Talk about food restrictions with Katie and confirm type of food- Anna
-  Follow up email to whole group - saying this is in two days. You should come.  - Stella
-  Print out RSVP list at Carbon Five - Anna
-  Google form for CFP - Lillie
-  Opening Closing Slides - Siena
-  Stickers - Lillie
- Question of the night
  - group will suggest via slack
  - print out question of night to have at check-in - Lillie

Day of 
- check-in - Siena
- everyone coming up at beginning
  -  Opening - code of conduct - Stella 
  - formal speaker introductions - ask all three the same three weird questions? (Ask speakers day of) - ?

Other - 
swearing policy - yes for now - depends on Michael Glass’s talks
video record - not for this time around

**Comment by lilliealbert** [comment]
Alright, it happened! People seemed to like it.

Some observations:
- Siena did some livetweeting / retweeting from the SF.rb account, which was very smart
- We should announce the hashtag at the beginning of the event! Maybe on the slide.
- The Italian food was very popular and Carbon Five were super gracious hosts.
- People were definitely ready for the talks by 7:05pm, and got quiet when the organizers stood in front (without being told to be quiet, it seems)
- We should ask speakers ahead of time if they want to do Q&A, and if so, announce ground rules
- Asking for help cleaning up / putting chairs away at 8:55pm was very effective
- If a speaker doesn't have slides, put up a dark background so they aren't washed out

@aneyzberg @sienatime @stellacotton Wanna publicly immortalize any other learnings?

**Comment by lilliealbert** [comment]
Also: 63 people came! 53 who RSVP'd, 10 who didn't (including one speaker) out of 75 total RSVPs. 84% is not bad! :100:

**Comment by aneyzberg** [comment]
We should make a note of the things we want to say in the intro and closing - such as we are accepting submissions via our CFP form, the date of our next event (if we have it), etc.

**Comment by sienaigg** [comment]
Yeah I'd say it was a resounding success! +1 to everything Lillie said.
- Check-in was pretty smooth, especially with the laptop cuz I could just Ctrl + F for people's names. There wasn't too much of a bottleneck at any given time and Emily (after graciously volunteering to check in any stragglers) said that nobody came after 7, so people even listened when we said to get there on time (and some people were early!)
- Stickers were very popular and we should definitely keep doing that
- We should pick a different hashtag for next time (possibly even make a unique one for each event, but that might be overkill) since it turns out #sfrb is also like science-fiction romance books, or something...
- Heard some chatter that the Hackbright alumnae who attended were very impressed and were spreading the word to more of their classmates, so that is v good
- I will probably not be here for the next one if we do it the last week of February (T__T) I come back Friday Feb. 26th
- We should do a photo disclaimer next time (with option to opt-out) so we can get some photos for public use/promotion of the meetup. Maybe we could just ask people who don't mind being in a photo to stand in a specific area and make it look like they're having fun or something? That would probably be least amount of effort. I'd like to have something for our Twitter hero image
- What can we do to empower first time speakers? Offer to help review their proposals? This is something that I in particular am interested in spearheading even if nobody else is (not saying you're not, just that I wouldn't mind leading the charge if that's what it takes)

**Comment by aneyzberg** [comment]
I agree with what both of you have said. and Siena would love to support you in helping get new speakers on board :) 

Also carbon five was really happy to host, and would love to host again. I would really like to get 4 or 5 companies we can rotate through. I can take the lead on the venue wrangling if that is helpful. Hopefully we can get several months of meetups scheduled in advance. 

I have also received personal emails from a couple of people who also said they are really looking forward to the next meetup! So to reiterate, it definitely went well!
